CREATE TABLE userinfo (
  id CHAR(36) NOT NULL PRIMARY KEY,
  email VARCHAR(255) DEFAULT NULL,
  fullname VARCHAR(255) DEFAULT NULL,
  role ENUM('ADMIN', 'PROFESSOR', 'STUDENT') DEFAULT 'STUDENT',
  password_hash VARCHAR(255) NOT NULL
);
