CREATE TABLE userinfo (
  id CHAR(36) NOT NULL PRIMARY KEY,
  email VARCHAR(255) DEFAULT NULL,
  fullname VARCHAR(255) DEFAULT NULL,
  is_admin BIT(1) DEFAULT NULL
);
ALTER TABLE userinfo
ADD password_hash VARCHAR(255) NOT NULL;
